In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("../data/raw/philippines_tech_jobs_raw.csv")
df.head()

,job_id,job_title,employer_name,employer_logo,employer_website,job_publisher,job_employment_type,job_employment_types,job_apply_link,job_apply_is_direct,...,job_salary_string,job_min_salary,job_max_salary,job_salary_period,job_highlights,job_onet_soc,job_onet_job_zone,employer_reviews,job_uid,search_role
0,RjBxQXYwdkUtbEM2VjBoREFBQUFBQT09OkVzd0JDb3dCUV...,CRM Junior Data Analyst,RUSTAN COMMERCIAL CORPORATION,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,Jobstreet,Full-time,['FULLTIME'],https://ph.jobstreet.com/job/94164327,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,F0qAv0vE-lC6V0hDAAAAAA==,Data Analyst
1,TG1zVUxHVHhNX3dyQU1raEFBQUFBQT09OkVzd0JDb3dCUV...,Finance Master Data Lead Analyst,Vestas Services Philippines Inc.,https://t0.gstatic.com/faviconV2?client=SOCIAL...,https://www.vestas.com,Jobstreet,Full-time,['FULLTIME'],https://ph.jobstreet.com/job/94176150,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,LmsULGTxM_wrAMkhAAAAAA==,Data Analyst
2,MVZzYl91azYwUGh0aTIxQUFBQUFBQT09OkVzd0JDb3dCUV...,CRM Data Analyst: Drive Personalization & Camp...,Home Credit Philippines,https://t0.gstatic.com/faviconV2?client=SOCIAL...,https://www.homecredit.ph,BeBee,Internship,['INTERN'],https://bebee.com/ph/jobs/crm-data-analyst-dri...,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,1Vsb_uk60Phti21AAAAAAA==,Data Analyst
3,T2FYOExQeTIyVGpKNlh1akFBQUFBQT09OkVzd0JDb3dCUV...,CRM Data Analyst — Insights for Precision Camp...,KadaKareer,https://t0.gstatic.com/faviconV2?client=SOCIAL...,https://www.kadakareer.com,BeBee,Full-time,['FULLTIME'],https://bebee.com/ph/jobs/crm-data-analyst-ins...,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,OaX8LPy22TjJ6XujAAAAAA==,Data Analyst
4,WWlGM3dHYUwxeFlLTktTN0FBQUFBQT09OkVzd0JDb3dCUV...,Senior Performance Data Analyst - 7471,International Education,https://t0.gstatic.com/faviconV2?client=SOCIAL...,NaN,Jobstreet,Full-time,['FULLTIME'],https://ph.jobstreet.com/job/93994083,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,YiF3wGaL1xYKNKS7AAAAAA==,Data Analyst

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 631 entries, 0 to 630
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      631 non-null    str
 1   job_title                   631 non-null    str
 2   employer_name               631 non-null    str
 3   employer_logo               496 non-null    str
 4   employer_website            317 non-null    str
 5   job_publisher               631 non-null    str
 6   job_employment_type         603 non-null    str
 7   job_employment_types        631 non-null    str
 8   job_apply_link              631 non-null    str
 9   job_apply_is_direct         631 non-null    bool
 10  apply_options               631 non-null    str
 11  job_description             631 non-null    str
 12  job_is_remote               631 non-null    bool
 13  job_posted_at               477 non-null    str
 14  job_posted_at_timestamp     477 non-null    float64
 15  job_posted_at_datetime_utc  477 non-null    str
 16  job_location                629 non-null    str
 17  job_city                    408 non-null    str
 18  job_state                   427 non-null    str
 19  job_country                 527 non-null    str
 20  job_latitude                527 non-null    float64
 21  job_longitude               527 non-null    float64
 22  job_benefits                0 non-null      float64
 23  job_benefits_strings        0 non-null      float64
 24  job_google_link             631 non-null    str
 25  job_salary                  0 non-null      float64
 26  job_salary_string           0 non-null      float64
 27  job_min_salary              0 non-null      float64
 28  job_max_salary              0 non-null      float64
 29  job_salary_period           0 non-null      float64
 30  job_highlights              631 non-null    str
 31  job_onet_soc                0 non-null      float64
 32  job_onet_job_zone           0 non-null      float64
 33  employer_reviews            0 non-null      float64
 34  job_uid                     631 non-null    str
 35  search_role                 631 non-null    str
dtypes: bool(2), float64(13), str(21)
memory usage: 169.0 KB

ROLE COUNTS

In [7]:
df["search_role"].value_counts()

search_role
Data Engineer        141
Data Analyst         139
Software Engineer    138
Cloud Engineer       126
Data Scientist        87
Name: count, dtype: int64

CHECK DUPLICATES

In [8]:
df["job_id"].duplicated().sum()

np.int64(0)

In [9]:
df.duplicated().sum()

np.int64(0)

MISSING VALUES

In [10]:
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)

print(missing_percentage)

job_min_salary                100.000000
job_onet_soc                  100.000000
job_salary_period             100.000000
job_max_salary                100.000000
job_benefits                  100.000000
job_benefits_strings          100.000000
job_onet_job_zone             100.000000
employer_reviews              100.000000
job_salary                    100.000000
job_salary_string             100.000000
employer_website               49.762282
job_city                       35.340729
job_state                      32.329635
job_posted_at_datetime_utc     24.405705
job_posted_at_timestamp        24.405705
job_posted_at                  24.405705
employer_logo                  21.394612
job_longitude                  16.481775
job_latitude                   16.481775
job_country                    16.481775
job_employment_type             4.437401
job_location                    0.316957
job_id                          0.000000
job_title                       0.000000
employer_name                   0.000000
job_apply_link                  0.000000
apply_options                   0.000000
job_description                 0.000000
job_is_remote                   0.000000
job_apply_is_direct             0.000000
job_publisher                   0.000000
job_employment_types            0.000000
job_google_link                 0.000000
job_highlights                  0.000000
job_uid                         0.000000
search_role                     0.000000
dtype: float64

In [11]:
df["job_country"].value_counts(dropna=False)

job_country
PH     527
NaN    104
Name: count, dtype: int64

In [12]:
country_missing = df[df["job_country"].isna()]

country_missing[
    [
        "search_role",
        "job_title",
        "employer_name",
        "job_location",
        "job_city",
        "job_state",
        "job_country"
    ]
].head(20)

,search_role,job_title,employer_name,job_location,job_city,job_state,job_country
138,Data Analyst,Data Analyst I (Channel Rebate Data Steward),Schneider Electric,Cavite,NaN,NaN,NaN
226,Data Engineer,Data engineer/ Analyst,"Prime@Technology Specialists, Inc.",Cavite,NaN,NaN,NaN
229,Data Engineer,"Director, Data Engineering",Manulife,"Lapu-Lapu, Cebu (+1 other)",NaN,NaN,NaN
235,Data Engineer,Data Engineer,Cambridge University Press,NaN,NaN,NaN,NaN
285,Data Engineer,"Cloud and Data Engineer (Legaspi, Albay) - Day...",TASQ Staffing Solutions,Bicol (+1 other),NaN,NaN,NaN
417,Cloud Engineer,Cloud Endpoint Support Engineer (Tier 2),HireArchi,Metro Manila (+1 other),NaN,NaN,NaN
418,Cloud Engineer,"Cloud Engineer: Build Resilient, Scalable Infra",Manpower (Philippines),"Valenzuela, Metro Manila",NaN,NaN,NaN
419,Cloud Engineer,Cloud Data Warehouse Engineer - Flexible Hours...,AS White Global,"Taguig, Metro Manila",NaN,NaN,NaN
420,Cloud Engineer,GCP Cloud Engineer (Google Cloud Platform),Brixio Singapore,Philippines,NaN,NaN,NaN
421,Cloud Engineer,"Cloud Network Engineer, Software Support",Copeland,"Quezon City, Metro Manila",NaN,NaN,NaN
422,Cloud Engineer,Senior .NET Cloud Engineer — AI‑Powered Azure ...,Intellectsoft,Philippines,NaN,NaN,NaN
423,Cloud Engineer,"AWS Cloud Engineer | IaC, CI/CD & Security",Orangeandbronze,"Makati City, Metro Manila",NaN,NaN,NaN
424,Cloud Engineer,Lead DevOps Engineer | Fully WFH,RecruitNest Consulting,Metro Manila (+1 other),NaN,NaN,NaN
425,Cloud Engineer,"Observability Engineer — Cloud, Kubernetes",Dsv Air & Sea SAU,"Manila, Metro Manila",NaN,NaN,NaN
426,Cloud Engineer,Lead Cloud Engineer - Infrastructure | REMOTE,TASQ Staffing Solutions,"Cebu City, Cebu",NaN,NaN,NaN
427,Cloud Engineer,Remote Cloud Engineer | AWS,NetCov PH,Davao Region,NaN,NaN,NaN
428,Cloud Engineer,Junior Cloud SRE: AWS,eTap Inc.,"Makati City, Metro Manila",NaN,NaN,NaN
429,Cloud Engineer,Senior Cloud Engineer (Openshift/AWS) - WFH/3 ...,Green Light Worldwide,Philippines,NaN,NaN,NaN
430,Cloud Engineer,Remote IT Systems Engineer: Lead Cloud,Intelligent Technical Solutions,"Quezon City, Metro Manila",NaN,NaN,NaN
431,Cloud Engineer,Senior AWS Cloud Engineer – Remote,TTEC Digital,"Pasig, Metro Manila",NaN,NaN,NaN

In [13]:
missing_all_location = df[
    df["job_country"].isna()
    & df["job_state"].isna()
    & df["job_city"].isna()
    & df["job_location"].isna()
]

print(missing_all_location.shape)

(2, 36)

In [14]:
missing_all_location[
    [
        "search_role",
        "job_title",
        "employer_name",
        "job_description",
        "job_location"
    ]
]

,search_role,job_title,employer_name,job_description,job_location
235,Data Engineer,Data Engineer,Cambridge University Press,Data Engineer\n\nWork setup: We operate in a h...,NaN
556,Software Engineer,"Software Engineer, Platform - Cebu, Philippines",Speechify,The mission of Speechify is to make sure that ...,NaN

In [15]:
description = missing_all_location.loc[235, "job_description"]

print("philippines" in description.lower())
print("manila" in description.lower())
print("cebu" in description.lower())

True
True
False

VERIFY DATES

In [16]:
df["job_posted_at_datetime_utc"] = pd.to_datetime(
    df["job_posted_at_datetime_utc"],
    errors="coerce"
)

In [17]:
print(df["job_posted_at_datetime_utc"].min())
print(df["job_posted_at_datetime_utc"].max())

2026-07-25 00:00:00+00:00
2026-08-25 01:00:00+00:00

### DATA CLEANING

In [18]:
print(df.columns.tolist())

['job_id', 'job_title', 'employer_name', 'employer_logo', 'employer_website', 'job_publisher', 'job_employment_type', 'job_employment_types', 'job_apply_link', 'job_apply_is_direct', 'apply_options', 'job_description', 'job_is_remote', 'job_posted_at', 'job_posted_at_timestamp', 'job_posted_at_datetime_utc', 'job_location', 'job_city', 'job_state', 'job_country', 'job_latitude', 'job_longitude', 'job_benefits', 'job_benefits_strings', 'job_google_link', 'job_salary', 'job_salary_string', 'job_min_salary', 'job_max_salary', 'job_salary_period', 'job_highlights', 'job_onet_soc', 'job_onet_job_zone', 'employer_reviews', 'job_uid', 'search_role']

In [19]:
columns_to_keep = [
    "job_id",
    "search_role",
    "job_title",
    "employer_name",
    "job_publisher",
    "job_employment_type",
    "job_description",
    "job_is_remote",
    "job_posted_at_datetime_utc",
    "job_location",
    "job_city",
    "job_state",
    "job_country"
]

df_clean = df[columns_to_keep].copy()

In [20]:
df_clean["job_posted_at_datetime_utc"] = pd.to_datetime(
    df_clean["job_posted_at_datetime_utc"],
    errors="coerce"
)

In [21]:
print(df_clean["job_employment_type"].value_counts(dropna=False))

job_employment_type
Full-time                   554
NaN                          28
Internship                   27
Contractor                   17
Part-time                     3
Full-time and Contractor      2
Name: count, dtype: int64

In [22]:
print(df_clean["job_is_remote"].value_counts(dropna=False))

job_is_remote
False    631
Name: count, dtype: int64

In [23]:
df_clean["location_clean"] = df_clean["job_location"]

df_clean["location_clean"] = df_clean["location_clean"].fillna(
    df_clean["job_city"]
)

df_clean["location_clean"] = df_clean["location_clean"].fillna(
    df_clean["job_state"]
)

In [24]:
df_clean.loc[
    df_clean["location_clean"].isna(),
    [
        "search_role",
        "job_title",
        "employer_name",
        "job_location",
        "job_city",
        "job_state",
        "job_country"
    ]
]

,search_role,job_title,employer_name,job_location,job_city,job_state,job_country
235,Data Engineer,Data Engineer,Cambridge University Press,NaN,NaN,NaN,NaN
556,Software Engineer,"Software Engineer, Platform - Cebu, Philippines",Speechify,NaN,NaN,NaN,NaN

In [25]:
df_clean.loc[556, "location_clean"] = "Cebu, Philippines"

In [26]:
df_clean.loc[235, "location_clean"] = "Makati, Philippines"

In [27]:
print(df_clean.info())

<class 'pandas.DataFrame'>
RangeIndex: 631 entries, 0 to 630
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      631 non-null    str
 1   search_role                 631 non-null    str
 2   job_title                   631 non-null    str
 3   employer_name               631 non-null    str
 4   job_publisher               631 non-null    str
 5   job_employment_type         603 non-null    str
 6   job_description             631 non-null    str
 7   job_is_remote               631 non-null    bool
 8   job_posted_at_datetime_utc  477 non-null    datetime64[us, UTC]
 9   job_location                629 non-null    str
 10  job_city                    408 non-null    str
 11  job_state                   427 non-null    str
 12  job_country                 527 non-null    str
 13  location_clean              631 non-null    str
dtypes: bool(1), datetime64[us, UTC](1), str(12)
memory usage: 64.8 KB
None

In [28]:
print(df_clean["job_employment_type"].value_counts(dropna=False))

job_employment_type
Full-time                   554
NaN                          28
Internship                   27
Contractor                   17
Part-time                     3
Full-time and Contractor      2
Name: count, dtype: int64

In [29]:
df_clean["job_employment_type"] = (
    df_clean["job_employment_type"]
    .fillna("Unknown")
    .str.strip()
)

In [30]:
columns_to_drop = [
    "job_min_salary",
    "job_max_salary",
    "job_salary",
    "job_salary_string",
    "job_salary_period",
    "job_benefits",
    "job_benefits_strings",
    "job_onet_soc",
    "job_onet_job_zone",
    "employer_reviews"
]

df_clean = df_clean.drop(columns=columns_to_drop, errors="ignore")

In [31]:
print(df_clean.columns.tolist())

['job_id', 'search_role', 'job_title', 'employer_name', 'job_publisher', 'job_employment_type', 'job_description', 'job_is_remote', 'job_posted_at_datetime_utc', 'job_location', 'job_city', 'job_state', 'job_country', 'location_clean']

# SKILL EXTRACTION

In [48]:
skills = [
    "Python",
    "SQL",
    "Power BI",
    "Tableau",
    "Excel",
    "AWS",
    "Azure",
    "GCP",
    "Spark",
    "PySpark",
    "Snowflake",
    "BigQuery",
    "Databricks",
    "Airflow",
    "dbt",
    "Looker",
    "Git",
    "Docker",
    "Kubernetes",

    # Software engineering
    "Java",
    "JavaScript",
    "TypeScript",
    "C#",
    "C++",
    "React",
    "Angular",
    "Node.js",

    # Databases / infrastructure
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Oracle",
    "Linux",
    "Terraform",

    # Data science / ML
    "Machine Learning",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn"
]

In [49]:
skill_rows = []

for _, row in df_clean.iterrows():

    text = (
        str(row["job_title"]) + " " +
        str(row["job_description"])
    ).lower()

    for skill in skills:

        if skill.lower() in text:

            skill_rows.append({
                "job_id": row["job_id"],
                "search_role": row["search_role"],
                "skill": skill
            })

In [50]:
df_skills = pd.DataFrame(skill_rows)

In [51]:
print(
    df_skills.duplicated(
        subset=["job_id", "skill"]
    ).sum()
)

print(df_skills["job_id"].nunique())

skill_coverage = (
    df_skills["job_id"].nunique()
    / df_clean["job_id"].nunique()
    * 100
)

print(skill_coverage)

0
542
85.89540412044374

In [54]:
matched_job_ids = df_skills["job_id"].unique()

unmatched_jobs = df_clean[
    ~df_clean["job_id"].isin(matched_job_ids)
]

print(unmatched_jobs.shape)

unmatched_jobs[
    [
        "search_role",
        "job_title",
        "job_description"
    ]
].head(30)

(89, 14)

,search_role,job_title,job_description
1,Data Analyst,Finance Master Data Lead Analyst,Global Master Data Management (MDM) is respons...
2,Data Analyst,CRM Data Analyst: Drive Personalization & Camp...,Job description\n\nHome Credit Philippines is ...
3,Data Analyst,CRM Data Analyst — Insights for Precision Camp...,Job description\n\nHome Credit Philippines is ...
7,Data Analyst,Senior Data Analyst: Strategic Insights,JLL in the Philippines is seeking a highly ski...
8,Data Analyst,Data Analyst Manager,DATA ANALYST MANAGER\n• Lead and manage data a...
9,Data Analyst,"Junior Data Analyst: Dashboards, KPIs","Rippedboxstation in Metro Manila, Philippines ..."
21,Data Analyst,Remote BI Data Analyst for AI Docs & Decks,Ethos is seeking an experienced business intel...
28,Data Analyst,Programme Data Analyst,World Vision International (New) is seeking a ...
29,Data Analyst,Data Analyst - Health Care,Must have experience in Homecare Homebase appl...
32,Data Analyst,CPA US Tax Data Analyst for AI Training & Data...,Gelt is seeking a US Tax Data Analyst in Manil...
33,Data Analyst,Data Analyst - Market & Reference Data Specialist,WTW Investments is a bespoke asset manager ser...
48,Data Analyst,Remote junior analytics specialist: data insights,Job description A leading analytics firm is lo...
52,Data Analyst,Senior data analyst: ai-driven insights (hybrid),Job description\n\nRemote: Hybrid\n\nRecruitif...
60,Data Analyst,HR Data Analyst,About the Role\n\nAre you interested in turnin...
63,Data Analyst,Junior Financial Data Analyst - Fresh Grad,ISS STOXX is seeking a Junior Data Analyst bas...
64,Data Analyst,Business Data Analyst - Senior Associate,Line of Service\nAdvisory\n\nIndustry/Sector\n...
65,Data Analyst,Data Analyst,"Business intelligence, reporting, and data vis..."
67,Data Analyst,Global FinTech Finance & Data Analyst,Arcadis in the Philippines seeks a Global FinT...
78,Data Analyst,Data Analyst II,Job Description\nThe Business Intelligence Dat...
80,Data Analyst,Market Data Ops Analyst,"Citco in Makati, PH, is seeking a Market Data ..."
81,Data Analyst,"Junior MIS Analyst: Data, Systems,",A financial services company in Metro Manila i...
82,Data Analyst,Data Analyst — Insights,GameSphere Solutions Inc. is seeking a Data An...
87,Data Analyst,Head of Data Analytics,- Lead analytics strategy and shape critical b...
97,Data Analyst,Data Analyst – Platform Migration,Data Analyst - Platform Migration\n\nAbout the...
104,Data Analyst,"Data Analyst I: Insights, Automation",RELX is seeking a Data Analyst to collaborate ...
125,Data Analyst,Strategic Supplier Data Analyst,"Arcadis, a leading global design, engineering ..."
148,Data Scientist,"Data Scientist: AI, NLP",Arch Insurance Group Inc. in Cebu City is seek...
161,Data Scientist,Technical Advisor – Industrial Data Science,Careers\n\nTechnical Advisor – Industrial Data...
164,Data Scientist,Data Scientist - AI & IDP for Claims Automation,Arch Global Services Philippines is seeking a ...
168,Data Scientist,Senior Data Scientist — LLM,EPAM is seeking a Senior Data Scientist with N...

In [55]:
unmatched_jobs[
    [
        "search_role",
        "job_title",
        "job_description"
    ]
].head(30)

,search_role,job_title,job_description
1,Data Analyst,Finance Master Data Lead Analyst,Global Master Data Management (MDM) is respons...
2,Data Analyst,CRM Data Analyst: Drive Personalization & Camp...,Job description\n\nHome Credit Philippines is ...
3,Data Analyst,CRM Data Analyst — Insights for Precision Camp...,Job description\n\nHome Credit Philippines is ...
7,Data Analyst,Senior Data Analyst: Strategic Insights,JLL in the Philippines is seeking a highly ski...
8,Data Analyst,Data Analyst Manager,DATA ANALYST MANAGER\n• Lead and manage data a...
9,Data Analyst,"Junior Data Analyst: Dashboards, KPIs","Rippedboxstation in Metro Manila, Philippines ..."
21,Data Analyst,Remote BI Data Analyst for AI Docs & Decks,Ethos is seeking an experienced business intel...
28,Data Analyst,Programme Data Analyst,World Vision International (New) is seeking a ...
29,Data Analyst,Data Analyst - Health Care,Must have experience in Homecare Homebase appl...
32,Data Analyst,CPA US Tax Data Analyst for AI Training & Data...,Gelt is seeking a US Tax Data Analyst in Manil...
33,Data Analyst,Data Analyst - Market & Reference Data Specialist,WTW Investments is a bespoke asset manager ser...
48,Data Analyst,Remote junior analytics specialist: data insights,Job description A leading analytics firm is lo...
52,Data Analyst,Senior data analyst: ai-driven insights (hybrid),Job description\n\nRemote: Hybrid\n\nRecruitif...
60,Data Analyst,HR Data Analyst,About the Role\n\nAre you interested in turnin...
63,Data Analyst,Junior Financial Data Analyst - Fresh Grad,ISS STOXX is seeking a Junior Data Analyst bas...
64,Data Analyst,Business Data Analyst - Senior Associate,Line of Service\nAdvisory\n\nIndustry/Sector\n...
65,Data Analyst,Data Analyst,"Business intelligence, reporting, and data vis..."
67,Data Analyst,Global FinTech Finance & Data Analyst,Arcadis in the Philippines seeks a Global FinT...
78,Data Analyst,Data Analyst II,Job Description\nThe Business Intelligence Dat...
80,Data Analyst,Market Data Ops Analyst,"Citco in Makati, PH, is seeking a Market Data ..."
81,Data Analyst,"Junior MIS Analyst: Data, Systems,",A financial services company in Metro Manila i...
82,Data Analyst,Data Analyst — Insights,GameSphere Solutions Inc. is seeking a Data An...
87,Data Analyst,Head of Data Analytics,- Lead analytics strategy and shape critical b...
97,Data Analyst,Data Analyst – Platform Migration,Data Analyst - Platform Migration\n\nAbout the...
104,Data Analyst,"Data Analyst I: Insights, Automation",RELX is seeking a Data Analyst to collaborate ...
125,Data Analyst,Strategic Supplier Data Analyst,"Arcadis, a leading global design, engineering ..."
148,Data Scientist,"Data Scientist: AI, NLP",Arch Insurance Group Inc. in Cebu City is seek...
161,Data Scientist,Technical Advisor – Industrial Data Science,Careers\n\nTechnical Advisor – Industrial Data...
164,Data Scientist,Data Scientist - AI & IDP for Claims Automation,Arch Global Services Philippines is seeking a ...
168,Data Scientist,Senior Data Scientist — LLM,EPAM is seeking a Senior Data Scientist with N...

In [56]:
print(unmatched_jobs.iloc[0]["job_title"])
print(unmatched_jobs.iloc[0]["job_description"])

Finance Master Data Lead Analyst
Global Master Data Management (MDM) is responsible for creating and maintaining a trusted view of a company's core business data (like Finance, Customer and other Masterdata Objects) across regions.

Finance SSC > Finance SSC - Specialized Finance > MDM

Responsibilities:

• Ensure that data processing is performed according to the processes (timely, complete, valid and accurate).

• Responsible for ensuring that other impacted master data and transaction data is consistent over all relevant systems

• Responsible for reviewing master data after entry to ensure accuracy and compliance with the change request.

• Analyzing change requests and requesting support from experts if required.

• Lead projects on improving Master Data processes and cleansing activities

• Improve data quality and participate in creation of data quality reports

• Responsible for documentation, which includes but is not limited to, process maps, workflow, Standard Operating Procedures (SOP), Manuals, Job Aids and presentations

• Responsible to participate or support in User Acceptance Testing (UAT) and activities when new process functionality is deployed.

• Responsible for training new MD administrators

Qualifications:

• Bachelor's Degree in any Finance, Business or Information technology course

• At least 3 years of work experience in Master Data Management

• Good methodological and communication skills

• Knowledge in using ERP System. Must have 3 years' SAP experience

• Experience in Finance and Customer master data is a plus

• Adhere to a fixed night shift schedule, supporting North America and Latin American countries

Competencies:

• Finance Master Data Lead Analyst is someone who has an operational role within the organization, and who can handle MD changes in the system

• Should have an affinity with master data management which implies an orderly and structured way of working / characteristics

• Should be updated on all rules and regulations which apply to a certain MD object

What we offer:

What We Offer Required We offer an exciting job with good opportunities for professional and personal development in an inspiring, innovative, motivated and international work environment in the renewable energy sector. We highly value initiative, accountability and the right balance between creativity and quality in all solutions. You will be a part of a professional international office and organization. You will have exciting global career opportunities in a department that is continuously developing.

Our commitment to a fair hiring.

At Vestas, we evaluate all candidates solely based on their professional experience, education, and relevant skills. To support a fair recruitment process, we kindly ask that you remove any photos, dates of birth or graduation, gender pronouns, marital status, or other personal information not relevant to the role before submitting your CV/resume. Your CV/resume should focus on your professional and educational background, along with the necessary contact details (email and phone number). We train our hiring teams in inclusive evaluation and regularly review process outcomes to ensure fairness.

DEIB Statement

At Vestas, we recognize the value of diversity, equity, and inclusion in driving innovation and success. We strongly encourage individuals from all backgrounds to apply, particularly those who may hesitate due to their identity or feel they do not meet every criterion. As our CEO states, "Expertise and talent come in many forms, and a diverse workforce enhances our ability to think differently and solve the complex challenges of our industry". Your unique perspective is what will help us powering the solution for a sustainable, green energy future.

BEWARE – RECRUITMENT FRAUD

It has come to our attention that there are a number of fraudulent emails from people pretending to work for Vestas. Read more via this link, https://www.vestas.com/en/careers/our-recruitment-process

About Vestas

Vestas is the energy industry’s global partner on sustainable energy solutions. We are specialised in designing, manufacturing, installing, and servicing wind turbines, both onshore and offshore.
Across the globe, we have installed more wind power than anyone else. We consider ourselves pioneers within the industry, as we continuously aim to design new solutions and technologies to create a more sustainable future for all of us. With more than 200 GW of wind power installed worldwide and 40+ years of experience in wind energy, we have an unmatched track record demonstrating our expertise within the field.
With 39,000 employees globally, we are a diverse team united by a common goal: to power the solution – today, tomorrow, and far into the future.
Vestas promotes a diverse workforce which embraces all social identities and is free of any discrimination. We commit to create and sustain an environment that acknowledges and harvests different experiences, skills, and perspectives. We also aim to give everyone equal access to opportunity.
To learn more about our company and life at Vestas, we invite you to visit our website at www.vestas.com and follow us on our social media channels. We also encourage you to join our Talent Universe to receive notifications on new and relevant postings.

In [57]:
print(unmatched_jobs.iloc[1]["job_title"])
print(unmatched_jobs.iloc[1]["job_description"])

CRM Data Analyst: Drive Personalization & Campaign Insights
Job description

Home Credit Philippines is seeking a data analyst to drive data-informed decisions for CRM initiatives. You will analyze CRM data, support targeted campaigns, and build insights that boost engagement and revenue.The role emphasizes data quality, segmentation, predictive modeling, and measurement through dashboards. Fresh grads or analysts with 1 year of experience are welcome to apply, with opportunities to grow in our international teams.

In [58]:
print(
    unmatched_jobs[
        ["search_role", "job_title"]
    ].to_string(index=False)
)

      search_role                                                            job_title
     Data Analyst                                     Finance Master Data Lead Analyst
     Data Analyst          CRM Data Analyst: Drive Personalization & Campaign Insights
     Data Analyst                  CRM Data Analyst — Insights for Precision Campaigns
     Data Analyst                              Senior Data Analyst: Strategic Insights
     Data Analyst                                                 Data Analyst Manager
     Data Analyst                                Junior Data Analyst: Dashboards, KPIs
     Data Analyst                           Remote BI Data Analyst for AI Docs & Decks
     Data Analyst                                               Programme Data Analyst
     Data Analyst                                           Data Analyst - Health Care
     Data Analyst               CPA US Tax Data Analyst for AI Training & Data Quality
     Data Analyst                    Data Analyst - Market & Reference Data Specialist
     Data Analyst                    Remote junior analytics specialist: data insights
     Data Analyst                     Senior data analyst: ai-driven insights (hybrid)
     Data Analyst                                                      HR Data Analyst
     Data Analyst                           Junior Financial Data Analyst - Fresh Grad
     Data Analyst                             Business Data Analyst - Senior Associate
     Data Analyst                                                         Data Analyst
     Data Analyst                                Global FinTech Finance & Data Analyst
     Data Analyst                                                      Data Analyst II
     Data Analyst                                              Market Data Ops Analyst
     Data Analyst                                   Junior MIS Analyst: Data, Systems,
     Data Analyst                                              Data Analyst — Insights
     Data Analyst                                               Head of Data Analytics
     Data Analyst                                    Data Analyst – Platform Migration
     Data Analyst                                 Data Analyst I: Insights, Automation
     Data Analyst                                      Strategic Supplier Data Analyst
   Data Scientist                                              Data Scientist: AI, NLP
   Data Scientist                          Technical Advisor – Industrial Data Science
   Data Scientist                      Data Scientist - AI & IDP for Claims Automation
   Data Scientist                                          Senior Data Scientist — LLM
   Data Scientist                                            Senior Data Scientist: AI
   Data Scientist                          Strategic Network Data Scientist – Insights
   Data Scientist                      Data Scientist, AI-Driven Decision Intelligence
   Data Scientist                              Lead, Data Science & Analytics (Hybrid)
   Data Scientist                         Remote Data Scientist — Government Analytics
    Data Engineer                                                  Data Engineer – EDP
    Data Engineer                                      AI-Driven Finance Data Engineer
    Data Engineer                                   Cloud Data Engineer: Pipelines, BI
    Data Engineer            Data Engineer: Deliver Scalable, Clean Data for Analytics
    Data Engineer Finance & Supply Chain Data Engineer - Build Scalable Data Solutions
    Data Engineer                          Data Architect {Data Landscape & Lakehouse}
    Data Engineer                                Data Engineer: Pipelines, Warehousing
    Data Engineer                                                   Data Engineer: ETL
   Cloud Engineer            Senior Genesys Cloud Engineer: Global Contact Center Lead
   Cloud Engineer                                Senior Partner Cloud Support Engineer
   Cloud Engineer                               Remote IT Systems Engineer: Lead Cloud
   Cloud Engineer                      Cloud Engineer: Build Resilient, Scalable Infra
   Cloud Engineer                               Remote IT Systems Engineer: Lead Cloud
   Cloud Engineer                            Remote IT Infrastructure Engineer – Cloud
   Cloud Engineer                                     Remote Lead Cloud Engineer — IaC
   Cloud Engineer                                   Remote MSP Infrastructure Engineer
   Cloud Engineer                                   Remote MSP Infrastructure Engineer
   Cloud Engineer                                   Remote MSP Infrastructure Engineer
   Cloud Engineer                                Senior Platform Engineer | Hybrid Ops
   Cloud Engineer                                     Remote Lead Cloud Engineer — IaC
   Cloud Engineer                                     Remote Lead Cloud Engineer — IaC
   Cloud Engineer                                        Remote Senior Microsoft Cloud
   Cloud Engineer                            Remote IT Infrastructure Engineer – Cloud
   Cloud Engineer                              Senior Cloud Analytics Engineering Lead
   Cloud Engineer                  Cloud Core Network Maintenance and Support Engineer
   Cloud Engineer                Senior Salesforce Developer: AI-Driven Cloud Engineer
   Cloud Engineer                           Senior Cloud ML Engineer, LLM Ops Platform
   Cloud Engineer                                Office-Based Systems Engineer – Cloud
   Cloud Engineer                               Remote IT Systems Engineer: Lead Cloud
   Cloud Engineer                                   Remote MSP Infrastructure Engineer
   Cloud Engineer                               Remote IT Systems Engineer: Lead Cloud
Software Engineer                Software Engineer - Build Tech for Good (Philippines)
Software Engineer                                             Junior Software Engineer
Software Engineer                               SOFTWARE ENGINEER (BACK-END DEVELOPER)
Software Engineer        Talent Database - Sr. QA Software Engineer - Philippines Only
Software Engineer                    Entry-Level Software Developer — AI/ML Enthusiast
Software Engineer                                     Mobile Banking Software Engineer
Software Engineer                                               Software Test Engineer
Software Engineer                              Software Engineer/Quality Test Engineer
Software Engineer                                         Head of Software Engineering
Software Engineer                              Full-Stack Software Engineer: AI, Cloud
Software Engineer                                                PHP Software Engineer
Software Engineer                       Remote Senior Software Developer (Philippines)
Software Engineer                                                       PERL Developer
Software Engineer                       Software Engineer I (Salesforce Administrator)
Software Engineer                          Custom Software Engineer SAP MM (Inventory)
Software Engineer                                        Junior IT Operations Engineer
Software Engineer                                             Remote Software Engineer
Software Engineer                               Senior Software Engineer: Cognitive AI
Software Engineer                                    Japanese Bridge Software Engineer
Software Engineer                   Full-Stack Engineer: Build Secure, Responsive Apps
Software Engineer             Backend Software Engineer - AI Neobank App (Philippines)
Software Engineer                              Secure Software Engineer – Applications
Software Engineer          Full Stack Software Engineer - AI Neobank App (Philippines)

In [59]:
row = unmatched_jobs.iloc[5]

print(row["job_title"])
print(row["job_description"])

Junior Data Analyst: Dashboards, KPIs
Rippedboxstation in Metro Manila, Philippines invites a Junior Data Analyst to join our data team. You will collect, clean, and analyze data from various systems, prepare recurring and ad-hoc reports, and help develop KPIs and dashboards to support management decisions. You will validate data quality, create visualizations, and work with business users to understand reporting needs in an Agile environment. Entry-level with 0–2 years of experience encouraged to apply.

In [68]:
df_clean.to_csv(
    "../processed/jobs_clean.csv",
    index=False
)

df_skills.to_csv(
    "../processed/job_skills.csv",
    index=False
)